[preface]
== 시작하며

세상은 데이터 속에서 헤엄치고 있습니다. 최근 몇년간 우리는 우리 시스템이 만들어내는 데이터의 양에
압도되어 왔습니다. 기존의 기술들은 어떻게 데이터를 저장하고 구조화 할것인지에 대해 초점을 맞추고
있습니다. 이것은 당신이 데이터로부터 실시간으로 추출되는 정보로 결정을 내려야하기 전까지는 괜찮습니다.

Elasticsearch는 분산된 확장가능한 실시간 검색/분석 엔진입니다. 당신이 검색과 분석, 데이터 조회를
가능하게하고, 때로는 당신이 프로젝트의 시작시에는 기대하지 않았던것을 가능하게 합니다. 이것은 또한
하드디스크에 들어있는 쓸모없는 raw 데이터를 위해 존재합니다.

당신이 자연어 검색(full text search)를 원하던 구조화된 데이터의 실시간 분석을 원하던 혹은 두가지 모두를
원하던, 이 책은 기본적인 Elasticsearch를 시작하는데 요구되는 기본적인 개념을 안내합니다. 기본개념을
소개한 뒤에, 요구사항을 해결하기 위해 마주치게되는 복잡한 검색 기능들을 소개합니다.

Elasticsearch는 단순한 자연어 검색 엔진이 아닙니다. 구조화된 검색, 분석, 쿼리 XXX
(query percolation), 위치정보와 자동완성, 추천(Suggest)의 사용법에 대해 설명합니다.
또한 Elasticsearch의 수평적 확장과 실서비스 단계로 넘어갈때의 설정과 모니터링에 대해서도 설명합니다.

=== Who should read this book

This book is for anybody who wants to put their data to work.  It doesn't
matter whether you are starting a new project and have the flexibility to
design the system from the ground up, or whether you need to give new life to
a legacy system.  Elasticsearch will help you to solve existing problems and
open the way to new features that you haven't yet considered.

This book is suitable for novices and experienced users alike. We expect you
to have some programming background and, although not required, it would help
to have used SQL and a relational database. We explain concepts from first
principles, helping novices to gain a sure footing in the complex world of
search.

The reader with a search background will also benefit from this book.
Elasticsearch is a new technology which has some familiar concepts.  The more
experienced user will gain an understanding of how those concepts have been
implemented and how they interact in the context of Elasticsearch. Even in the
early chapters, there are nuggets of information that will be useful to the
more advanced user.

Finally, maybe you are in DevOps. While the other departments are stuffing
data into Elasticsearch as fast as they can, you're the one charged with
stopping their servers from bursting into flames. Elasticsearch scales
effortlessly, as long as your users play within the rules. You need to know
how to setup a stable cluster before going into production, then be able to
recognize the warning signs at 3am in the morning in order to prevent
catastrophe. The earlier chapters may be of less interest to you but the last
part of the book is essential reading -- all you need to know to avoid
meltdown.


=== Why we wrote this book

We wrote this book because Elasticsearch needs a narrative.  The existing
reference documentation is excellent... as long as you know what you are
looking for. It assumes that you are intimately familiar with information
retrieval concepts, distributed systems, the query DSL and a host of other
topics.

This book makes no such assumptions.  It has been written so that a complete
beginner -- to both search and distributed systems -- can pick it up and start
building a prototype within a few chapters.

We have taken a problem based approach: this is the problem, how do I solve
it, and what are the trade-offs of the alternative solutions? We start with the
basics and each chapter builds on the preceding ones, providing practical
examples and explaining the theory where necessary.

The existing reference documentation explains *how* to use features.  We want
this book to explain *why* and *when* to use various features.

=== How to read this book

Elasticsearch tries very hard to make the complex simple, and to a large
degree it succeeds in this. That said, search and distributed systems *are*
complex and sooner or later you have to get to grips with some of the
complexity in order to take full advantage of Elasticsearch.

Complexity, however, is not the same as magic.  We tend to view complex
systems as magical black boxes that respond to incantations, but there are
usually simple processes at work within. Understanding these processes helps
to disspell the magic -- instead of hoping that the black box will do what you
want, understanding gives you certainty and clarity.

This is a definitive guide: not only do we help you to get started with
Elasticsearch, we tackle the deeper more interesting topics too. These include
chapters such as <<distributed-cluster>>, <<distributed-docs>> and
<<distributed-search>>, which are not essential reading but do give you a solid
understanding of the internals.

The first part of the book should be read in order as each chapter builds on
the previous chapter (although you can skim over the chapters mentioned
above).  Later chapters like <<partial-matching>> and <<proximity-matching>>
are more standalone and can be referred to as needed.

=== Navigating this book

This book is divided into five parts:

*  Chapters 1 through 10 provide an introduction to Elasticsearch. They
   explain how to get your data in and out of Elasticsearch, how Elasticsearch
   interprets the data in your documents, how basic search works and how to
   manage indices. By the end of this section you will already be able to
   integrate your application with Elasticsearch. Chapters 2, 4 and 9 are
   supplemental chapters which provide more insight into the distributed
   processes at work, but are not required reading.

*  Chapters 11 through 21 offer a deep dive into search -- how to index and
   query your data to allow  you to take advantage of more advanced concepts
   like word proximity, partial matching, fuzzy matching and language
   awareness. You will understand how relevance works and how to control it
   to ensure that the best results are on the first page.

*  Chapters 22 through 25 tackle subjects such as aggregations or analytics,
   geolocation, query percolation and scripting.

*  Chapters 26 through 28 teach you how to understand the flow of data through
   your system and how to model your data to work well with the infrastructure
   provided by Elasticsearch.

*  Finally, chapters 29 through 31 discuss moving to production: the important
   configurations, what to monitor, and how to diagnose and prevent problems.


=== Online Resources

Because this book focuses on problem solving in Elasticsearch rather than syntax, we sometimes reference the existing documentation for a complete
list of parameters.  The reference documentation can be found here:

http://www.elasticsearch.org/guide/

=== Conventions Used in This Book

The following typographical conventions are used in this book:

_Italic_:: Indicates new terms or concepts.

+Constant width+:: Used for program listings, as well as within paragraphs to refer to program elements such as variable or function names, databases, data types, environment variables, statements, and keywords.


[TIP]
====
This icon signifies a tip, suggestion, or general note.
====

[WARNING]
====
This icon indicates a warning or caution.
====

=== Using Code Examples
////
Do not edit this section.
////
++++
<remark>PROD: Please reach out to author to find out if they will be uploading code examples to oreilly.com or their own site (e.g., GitHub). If there is no code download, delete this whole section. If there is, when you email digidist with the link, let them know what you filled in for title_title (should be as close to book title as possible, i.e., learning_python_2e). This info will determine where digidist loads the files.</remark>
++++

Supplemental material (code examples, exercises, etc.) is available for download at link:$$https://github.com/oreillymedia/title_title$$[].

This book is here to help you get your job done. In general, if example code is offered with this book, you may use it in your programs and documentation. You do not need to contact us for permission unless you’re reproducing a significant portion of the code. For example, writing a program that uses several chunks of code from this book does not require permission. Selling or distributing a CD-ROM of examples from O’Reilly books does require permission. Answering a question by citing this book and quoting example code does not require permission. Incorporating a significant amount of example code from this book into your product’s documentation does require permission.

We appreciate, but do not require, attribution. An attribution usually includes the title, author, publisher, and ISBN. For example: “_Elasticsearch - The Definitive Guide_ by Clinton Gormley and Zachary Tony (O’Reilly). Copyright 2014 Elasticsearch BV, 978-0-596-xxxx-x.”

If you feel your use of code examples falls outside fair use or the permission given above, feel free to contact us at pass:[<email>permissions@oreilly.com</email>].

=== Safari® Books Online
////
Do not edit this section.
////
[role = "safarienabled"]
[NOTE]
====
pass:[<ulink role="orm:hideurl:ital" url="http://my.safaribooksonline.com/?portal=oreilly">Safari Books Online</ulink>] is an on-demand digital library that delivers expert pass:[<ulink role="orm:hideurl" url="http://www.safaribooksonline.com/content">content</ulink>] in both book and video form from the world&#8217;s leading authors in technology and business.
====

Technology professionals, software developers, web designers, and business and creative professionals use Safari Books Online as their primary resource for research, problem solving, learning, and certification training.

Safari Books Online offers a range of pass:[<ulink role="orm:hideurl" url="http://www.safaribooksonline.com/subscriptions">product mixes</ulink>] and pricing programs for pass:[<ulink role="orm:hideurl" url="http://www.safaribooksonline.com/organizations-teams">organizations</ulink>], pass:[<ulink role="orm:hideurl" url="http://www.safaribooksonline.com/government">government agencies</ulink>], and pass:[<ulink role="orm:hideurl" url="http://www.safaribooksonline.com/individuals">individuals</ulink>]. Subscribers have access to thousands of books, training videos, and prepublication manuscripts in one fully searchable database from publishers like O’Reilly Media, Prentice Hall Professional, Addison-Wesley Professional, Microsoft Press, Sams, Que, Peachpit Press, Focal Press, Cisco Press, John Wiley & Sons, Syngress, Morgan Kaufmann, IBM Redbooks, Packt, Adobe Press, FT Press, Apress, Manning, New Riders, McGraw-Hill, Jones & Bartlett, Course Technology, and dozens pass:[<ulink role="orm:hideurl" url="http://www.safaribooksonline.com/publishers">more</ulink>]. For more information about Safari Books Online, please visit us pass:[<ulink role="orm:hideurl" url="http://www.safaribooksonline.com/">online</ulink>].

=== How to Contact Us
////
Do not edit this section.
////
Please address comments and questions concerning this book to the publisher:

++++
<simplelist>
<member>O’Reilly Media, Inc.</member>
<member>1005 Gravenstein Highway North</member>
<member>Sebastopol, CA 95472</member>
<member>800-998-9938 (in the United States or Canada)</member>
<member>707-829-0515 (international or local)</member>
<member>707-829-0104 (fax)</member>
</simplelist>
++++

We have a web page for this book, where we list errata, examples, and any additional information. You can access this page at link:$$http://www.oreilly.com/catalog/0636920028505$$[].

++++
<remark>Don't forget to update the link above.</remark>
++++

To comment or ask technical questions about this book, send email to pass:[<email>bookquestions@oreilly.com</email>].

For more information about our books, courses, conferences, and news, see our website at link:$$http://www.oreilly.com$$[].

Find us on Facebook: link:$$http://facebook.com/oreilly$$[]

Follow us on Twitter: link:$$http://twitter.com/oreillymedia$$[]

Watch us on YouTube: link:$$http://www.youtube.com/oreillymedia$$[]

////
=== Acknowledgments

This is where you'll dedicate the book to those who helped, supported, and sacrificed as you created the book, and possibly dear pets, too.
////

++++
<remark>Fill in...</remark>
++++